sudo: required
dist: trusty
language: node_js
node_js:
  - 'lts/*'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - sh -e /etc/init.d/xvfb start
